package com.blog.pojo;

import java.util.Date;
import java.util.List;

public class Post {

    private String postID;
    private String content;
    private List<String> tags;
    private String blogID;
    private int numOfViews;
    private Date createdOn;
    private Date modifiedOn;

    public Post() {
    }
    public Post(String content, String blogID) {
        this();
        this.content = content;
        this.createdOn = new Date();
        this.blogID = blogID;

    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getPostID() {
        return postID;
    }
    public void setPostID(String postID) {
        this.postID = postID;
    }

    @DynamoDBAttribute
    public String getContent() {
        return content;
    }
    public void setContent(String content) {
        this.content = content;
    }

    @DynamoDBAttribute
    public List<String> getTags() {
        return tags;
    }
    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    @DynamoDBAttribute
    public String getBlogID() {
        return blogID;
    }
    public void setBlogID(String blogID) {
        this.blogID = blogID;
    }

    @DynamoDBAttribute
    public int getNumOfViews() {
        return numOfViews;
    }
    public void setNumOfViews(int numOfViews) {
        this.numOfViews = numOfViews;
    }

    @DynamoDBAutoGeneratedTimestamp
    public Date getCreatedOn() {
        return createdOn;
    }
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @DynamoDBAttribute
    public Date getModifiedOn() {
        return modifiedOn;
    }
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((blogID == null) ? 0 : blogID.hashCode());
        result = prime * result + ((content == null) ? 0 : content.hashCode());
        result = prime * result + numOfViews;
        result = prime * result + ((postID == null) ? 0 : postID.hashCode());
        result = prime * result + ((tags == null) ? 0 : tags.hashCode());
        return result;
    }
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Post other = (Post) obj;
        if (blogID == null) {
            if (other.blogID != null)
                return false;
        } else if (!blogID.equals(other.blogID))
            return false;
        if (content == null) {
            if (other.content != null)
                return false;
        } else if (!content.equals(other.content))
            return false;
        if (numOfViews != other.numOfViews)
            return false;
        if (postID == null) {
            if (other.postID != null)
                return false;
        } else if (!postID.equals(other.postID))
            return false;
        if (tags == null) {
            if (other.tags != null)
                return false;
        } else if (!tags.equals(other.tags))
            return false;
        return true;
    }
    @Override
    public String toString() {
        return "Post [postID=" + postID + ", content=" + content + ", tags=" + tags + ", blogID=" + blogID + ", numOfViews=" + numOfViews + "]";
    }
}